backend:
  name: github
  repo: chobble-mirror/surge-test
  branch: main
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
